= On Fedora Workstation

sudo livecd-iso-to-disk --format --reset-mbr Fedora-Workstation-Live-x86_64-32-1.6.iso /dev/sdb1



https://www.reddit.com/r/Fedora/comments/3udmf9/sleep_and_hibernation/
https://extensions.gnome.org/extension/826/suspend-button/

* To suspend from the CLI: systemctl suspend
* To susped from the GUI: Hold <Alt> when the top-right menu is open


== How to install podman on Fedora
https://podman.io/getting-started/installation.html
[source,bash]
----
sudo yum -y install podman
----


== Change window in main screen
Ctrl + Alt + up/down


== How to shutdonw Fedora from command line
[source,bash]
----
systemctl poweroff -i
----


== How to reboot Fedora from command line
[source,bash]
----
sudo reboot

or

systemctl reboot -i
----


== How to disable Tracker on Fedora
* Search를 위한 indexing 작업이 cpu를 소모하므로 disable 시키자.
* https://www.linuxuprising.com/2019/07/how-to-completely-disable-tracker.html
* Settings -> Search 로 가서 화면 맨위에 버튼을 disable 시키자.
** 그래도 안되서 강제 disable
----
systemctl --user mask tracker-store.service tracker-miner-fs.service tracker-miner-rss.service tracker-extract.service tracker-miner-apps.service tracker-writeback.service

tracker reset --hard

~~~
Unit tracker-miner-apps.service does not exist, proceeding anyway.
Created symlink /home/jwon/.config/systemd/user/tracker-store.service → /dev/null.
Created symlink /home/jwon/.config/systemd/user/tracker-miner-fs.service → /dev/null.
Created symlink /home/jwon/.config/systemd/user/tracker-miner-rss.service → /dev/null.
Created symlink /home/jwon/.config/systemd/user/tracker-extract.service → /dev/null.
Created symlink /home/jwon/.config/systemd/user/tracker-miner-apps.service → /dev/null.
Created symlink /home/jwon/.config/systemd/user/tracker-writeback.service → /dev/null.
CAUTION: This process may irreversibly delete data.
Although most content indexed by Tracker can be safely reindexed, it can’t be assured that this is the case for all data. Be aware that you may be incurring in a data loss situation, proceed at your own risk.

Are you sure you want to proceed? [y|N]: y
Found 2 PIDs…
  Killed process 2696 — “tracker-miner-fs”
  Killed process 2704 — “tracker-extract”
_g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
Setting database locations
Checking database directories exist
Checking database version
Checking whether database files exist
Removing all database/storage files
  Removing database:'/home/jwon/.cache/tracker/meta.db'
  Removing db-locale file:'/home/jwon/.cache/tracker/db-locale.txt'
  Removing journal:'/home/jwon/.local/share/tracker/data/tracker-store.journal'
  Removing db-version file:'/home/jwon/.cache/tracker/db-version.txt'
~~~

그리고 reboot
----
* 다시 enable 하고 싶으면
----
systemctl --user unmask tracker-store.service tracker-miner-fs.service tracker-miner-rss.service tracker-extract.service tracker-miner-apps.service tracker-writeback.service

그리고 reboot
----


== High CPU tracker-miner-fs on Fedora
* file search를 위한 indexing 작업 수행
* https://askbot.fedoraproject.org/en/question/9822/how-do-i-disable-tracker-in-gnome/
* Disable 하려면
----
gsettings set org.freedesktop.Tracker.Miner.Files enable-monitors false
----

* https://www.linuxuprising.com/2019/07/how-to-completely-disable-tracker.html


== How to maximize a window
* Super + upper key


== How to move application windows across screens
* Super + Shift + <- or


== Keyboard Shorcuts for Fedora
* Fedora GNOME Keyboard Shortcuts
** https://kinesis-ergo.com/support/advantage2/


=== Close window
* Super + Q

== How to take screenshots
* Go to search bar
* Find screenshotP


== Fedora Productivity Tools
* https://www.dedoimedo.com/computers/fedora-30-after-install.html
* https://blog.hubstaff.com/11-linux-productivity-tools/
* https://www.dedoimedo.com/computers/gnome-customization.html
* https://www.dedoimedo.com/computers/gnome-edit-theme.html
* https://gitlab.com/LinxGem33/Arc-Menu


== How to install Dash to Dock on Fedora
* https://www.dedoimedo.com/computers/gnome-3-dash-to-panel.html
* https://extensions.gnome.org/extension/307/dash-to-dock/
** Need to open by FireFox, not Chrome to install
*** Chrome: "You can see "We cannot detect a running copy of GNOME on this system, so some parts of the interface may be disabled. See our troubleshooting entry for more information."


== How to change the color of your Linux terminal | Opensource.com
https://opensource.com/article/19/9/linux-terminal-colors


== How to install OpenJDK 8 on Fedora
[source,sh,options="nowrap"]
----
sudo dnf search openjdk
sudo dnf search openjdk | grep 1.8
sudo dnf install java-1.8.0-openjdk-devel.x86_64
sudo dnf install java-1.8.0-openjdk-src.x86_64
----


== How to install Docker on Fedora
https://docs.docker.com/install/linux/docker-ce/fedora/

----
sudo systemctl start docker
----


== How to record output sound on Fedora
* 일단 내 목소리 빼고 녹음하는데 성공! 아래 링크를 따라서 실행한다.
* https://www.addictivetips.com/ubuntu-linux-tips/record-speaker-output-on-linux/
** sudo dnf install pavucontrol audacity 설치하고
** “Pavu Control” and “Audacity” 앱 실행하고
** “Pavu Control” 의 Configuration 메뉴에서 Output 으로 선택하고
** “Audacity” 에서 record 버튼 클릭하면 끝!


== Set up Printers

=== For All
https://redhat.service-now.com/help?id=kb_article_view&sysparm_article=KB0004636&sys_kb_id=a11b19681b94ac10df470f69cc4bcb75#GettingStarted


=== For Fedora
https://redhat.service-now.com/help?id=kb_article_view&sysparm_article=KB0004651&sys_kb_id=e03697661b40a01040d63267cc4bcb0c


== Brisbane office Printers
http://cups.bne.redhat.com:631/printers/